---
description: Compilerfehler CS0724
title: Compilerfehler CS0724
ms.date: 07/20/2015
f1_keywords:
- CS0724
helpviewer_keywords:
- CS0724
ms.assetid: bcdb2017-7a43-4242-b4e2-a1ae03d6d73f
ms.openlocfilehash: 88510a423e47ee4eb3a19eca1b4911a451d6513a
ms.sourcegitcommit: d579fb5e4b46745fd0f1f8874c94c6469ce58604
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 08/30/2020
ms.locfileid: "89119754"
---
# <a name="compiler-error-cs0724"></a><span data-ttu-id="bc6d9-103">Compilerfehler CS0724</span><span class="sxs-lookup"><span data-stu-id="bc6d9-103">Compiler Error CS0724</span></span>

<span data-ttu-id="bc6d9-104">In einer finally-Klausel, die in der nächsten einschließenden catch-Klausel geschachtelt ist, ist keine throw-Anweisung ohne Argumente zulässig.</span><span class="sxs-lookup"><span data-stu-id="bc6d9-104">A throw statement with no arguments is not allowed in a finally clause that is nested inside the nearest enclosing catch clause</span></span>

## <a name="example"></a><span data-ttu-id="bc6d9-105">Beispiel</span><span class="sxs-lookup"><span data-stu-id="bc6d9-105">Example</span></span>

<span data-ttu-id="bc6d9-106">Im folgenden Beispiel wird CS0724 aufgrund der- `throw` Anweisung innerhalb des- `finally` klauselblocks generiert:</span><span class="sxs-lookup"><span data-stu-id="bc6d9-106">The following example generates CS0724 because of the `throw` statement inside the `finally` clause block:</span></span>

```csharp  
// CS0724.cs  
using System;  
  
class Program
{
    static void Test()
    {
        try
        {
            throw new Exception();
        }
        catch
        {
            try
            {
            }
            finally
            {
                throw; // CS0724
            }
        }
    }

    static void Main()
    {
    }
}
```
