---
title: "'Exit Try' kann nur innerhalb einer Try-Anweisung verwendet werden."
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: 05df59cb710c83eada1eba4b7ddb1323fa0dd217
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 09/23/2020
ms.locfileid: "91082180"
---
# <a name="exit-try-can-only-appear-inside-a-try-statement"></a>'Exit Try' kann nur innerhalb einer Try-Anweisung verwendet werden.

`Exit Try` kann nur innerhalb einer `Try` -Blockanweisung angezeigt werden. Entweder ist die `Exit Try` -Anweisung redundant, oder die `Exit Try` -Anweisung befindet sich außerhalb des entsprechenden `Try` -Blocks.  
  
 **Fehler-ID:** BC30393  
  
## <a name="to-correct-this-error"></a>So beheben Sie diesen Fehler  
  
1. Suchen und entfernen Sie die unnötige `Exit Try` -Anweisung.  
  
2. Verschieben Sie die- `Exit Try` Anweisung an die entsprechende Stelle innerhalb des Codes.  
  
## <a name="see-also"></a>Siehe auch

- [Try... Catch... Abschließend-Anweisung](../language-reference/statements/try-catch-finally-statement.md)
