---
title: Die Throw-Anweisung kann außerhalb einer Catch-Anweisung oder innerhalb einer Finally-Anweisung den Operanden nicht auslassen.
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: 05fc14b0f493b3901fda9fbdba7e0fcebae6bea5
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 09/23/2020
ms.locfileid: "91068894"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a><span data-ttu-id="f5e89-102">Die Throw-Anweisung kann außerhalb einer Catch-Anweisung oder innerhalb einer Finally-Anweisung den Operanden nicht auslassen.</span><span class="sxs-lookup"><span data-stu-id="f5e89-102">'Throw' statement cannot omit operand outside a 'Catch' statement or inside a 'Finally' statement</span></span>

<span data-ttu-id="f5e89-103">`Throw` -Anweisungen außerhalb einer `Catch` -Anweisung müssen den Namen eines Ausnahmeobjekts angeben.</span><span class="sxs-lookup"><span data-stu-id="f5e89-103">`Throw` statements outside of `Catch` statement must supply the name of an exception object.</span></span>  
  
 <span data-ttu-id="f5e89-104">**Fehler-ID:** BC30666</span><span class="sxs-lookup"><span data-stu-id="f5e89-104">**Error ID:** BC30666</span></span>  
  
## <a name="to-correct-this-error"></a><span data-ttu-id="f5e89-105">So beheben Sie diesen Fehler</span><span class="sxs-lookup"><span data-stu-id="f5e89-105">To correct this error</span></span>  
  
1. <span data-ttu-id="f5e89-106">Geben Sie den Namen eines von `System.Exception`abgeleiteten Ausnahmeobjekts an.</span><span class="sxs-lookup"><span data-stu-id="f5e89-106">Specify the name of an exception object derived from `System.Exception`.</span></span>  
  
2. <span data-ttu-id="f5e89-107">Strukturieren Sie den Code neu, damit sich die `Throw` -Anweisung innerhalb eines `Catch` -Blocks befindet.</span><span class="sxs-lookup"><span data-stu-id="f5e89-107">Restructure your code so that the `Throw` statement is inside a `Catch` block.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="f5e89-108">Siehe auch</span><span class="sxs-lookup"><span data-stu-id="f5e89-108">See also</span></span>

- [<span data-ttu-id="f5e89-109">Throw-Anweisung</span><span class="sxs-lookup"><span data-stu-id="f5e89-109">Throw Statement</span></span>](../language-reference/statements/throw-statement.md)
- [<span data-ttu-id="f5e89-110">Try...Catch...Finally-Anweisung</span><span class="sxs-lookup"><span data-stu-id="f5e89-110">Try...Catch...Finally Statement</span></span>](../language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [<span data-ttu-id="f5e89-111">Behandeln und Auslösen von Ausnahmen in .NET</span><span class="sxs-lookup"><span data-stu-id="f5e89-111">Handling and throwing exceptions in .NET</span></span>](../../standard/exceptions/index.md)
