---
title: Der Catch-Block wird niemals erreicht; "<exception>" wird oben in der gleichen Try-Anweisung behandelt
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: 5133bfd9b4471350691407dee09feec2d3af444a
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 09/23/2020
ms.locfileid: "91084553"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a>Der Catch-Block wird niemals erreicht; "\<exception>" wird oben in der gleichen Try-Anweisung behandelt

Ein `Catch` -Block im Code kann nicht erreicht werden, weil er in einem vorhergehenden `Try` -Block behandelt wird.  
  
Standardmäßig ist diese Meldung eine Warnung. Weitere Informationen zum Ausblenden von Warnungen oder zum Behandeln von Warnungen als Fehler finden Sie unter [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).
  
 **Fehler-ID:** BC42031  
  
## <a name="to-correct-this-error"></a>So beheben Sie diesen Fehler  
  
- Entfernen Sie die redundante Anweisung.  
  
## <a name="see-also"></a>Siehe auch

- [Verwenden des try/catch-Blocks zum Abfangen von Ausnahmen](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Verwenden benutzergefilterter Ausnahmehandler](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [Try... Catch... Abschließend-Anweisung](../language-reference/statements/try-catch-finally-statement.md)
