---
title: 'Vorgehensweise: Behandeln einer Ausnahme mit „try/catch“ (C#-Programmierleitfaden)'
description: Erfahren Sie, wie Sie eine Ausnahme mit einem try-catch-Block behandeln. Hier finden Sie ein Codebeispiel und zusätzliche verfügbare Ressourcen.
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#], try/catch blocks
- exceptions [C#], try/catch blocks
- try/catch blocks [C#]
ms.assetid: ca8e3773-980e-4767-8633-7408540e9818
ms.openlocfilehash: 357aebe042bc5b6e761b3c1bad258021441de22c
ms.sourcegitcommit: 6f58a5f75ceeb936f8ee5b786e9adb81a9a3bee9
ms.translationtype: HT
ms.contentlocale: de-DE
ms.lasthandoff: 07/28/2020
ms.locfileid: "87301995"
---
# <a name="how-to-handle-an-exception-using-trycatch-c-programming-guide"></a><span data-ttu-id="b068c-104">Vorgehensweise: Behandeln einer Ausnahme mit „try/catch“ (C#-Programmierleitfaden)</span><span class="sxs-lookup"><span data-stu-id="b068c-104">How to handle an exception using try/catch (C# Programming Guide)</span></span>
<span data-ttu-id="b068c-105">Ein [try/catch](../../language-reference/keywords/try-catch.md)-Block soll von Arbeitscode generierte Ausnahmen abfangen und verarbeiten.</span><span class="sxs-lookup"><span data-stu-id="b068c-105">The purpose of a [try-catch](../../language-reference/keywords/try-catch.md) block is to catch and handle an exception generated by working code.</span></span> <span data-ttu-id="b068c-106">Einige Ausnahmen können in einem `catch`-Block verarbeitet werden, und das Problem kann behoben werden, ohne dass die Ausnahme erneut ausgelöst wird. Allerdings können Sie meistens nur sicherstellen, dass die passende Ausnahme ausgelöst wird.</span><span class="sxs-lookup"><span data-stu-id="b068c-106">Some exceptions can be handled in a `catch` block and the problem solved without the exception being re-thrown; however, more often the only thing that you can do is make sure that the appropriate exception is thrown.</span></span>  
  
## <a name="example"></a><span data-ttu-id="b068c-107">Beispiel</span><span class="sxs-lookup"><span data-stu-id="b068c-107">Example</span></span>  
 <span data-ttu-id="b068c-108">In diesem Beispiel ist <xref:System.IndexOutOfRangeException> nicht die passendste Ausnahme: Für diese Methode ist <xref:System.ArgumentOutOfRangeException> sinnvoller, da der Fehler durch die Übergabe des Arguments `index` des Aufrufers verursacht wird.</span><span class="sxs-lookup"><span data-stu-id="b068c-108">In this example, <xref:System.IndexOutOfRangeException> is not the most appropriate exception: <xref:System.ArgumentOutOfRangeException> makes more sense for the method because the error is caused by the `index` argument passed in by the caller.</span></span>  
  
 [!code-csharp[csProgGuideExceptions#5](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#5)]  
  
## <a name="comments"></a><span data-ttu-id="b068c-109">Kommentare</span><span class="sxs-lookup"><span data-stu-id="b068c-109">Comments</span></span>  
 <span data-ttu-id="b068c-110">Der Code, der eine Ausnahme auslöst, ist im `try`-Block eingeschlossen.</span><span class="sxs-lookup"><span data-stu-id="b068c-110">The code that causes an exception is enclosed in the `try` block.</span></span> <span data-ttu-id="b068c-111">Eine `catch`-Anweisung wird direkt danach hinzugefügt, um `IndexOutOfRangeException` zu verarbeiten, falls dies auftritt.</span><span class="sxs-lookup"><span data-stu-id="b068c-111">A `catch` statement is added immediately after to handle `IndexOutOfRangeException`, if it occurs.</span></span> <span data-ttu-id="b068c-112">Der `catch`-Block verarbeitet `IndexOutOfRangeException` und löst stattdessen die passendere Ausnahme `ArgumentOutOfRangeException` aus.</span><span class="sxs-lookup"><span data-stu-id="b068c-112">The `catch` block handles the `IndexOutOfRangeException` and throws the more appropriate `ArgumentOutOfRangeException` exception instead.</span></span> <span data-ttu-id="b068c-113">Um dem Aufrufer so viele Informationen wie möglich bereitzustellen, können Sie die ursprüngliche Ausnahme auf <xref:System.Exception.InnerException%2A> der neuen Ausnahme festlegen.</span><span class="sxs-lookup"><span data-stu-id="b068c-113">In order to provide the caller with as much information as possible, consider specifying the original exception as the <xref:System.Exception.InnerException%2A> of the new exception.</span></span> <span data-ttu-id="b068c-114">Da die Eigenschaft <xref:System.Exception.InnerException%2A> [schreibgeschützt](../../properties.md#read-only) ist, müssen Sie sie im Konstruktor der neuen Ausnahme zuweisen.</span><span class="sxs-lookup"><span data-stu-id="b068c-114">Because the <xref:System.Exception.InnerException%2A> property is [read-only](../../properties.md#read-only), you must assign it in the constructor of the new exception.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="b068c-115">Weitere Informationen</span><span class="sxs-lookup"><span data-stu-id="b068c-115">See also</span></span>

- [<span data-ttu-id="b068c-116">C#-Programmierhandbuch</span><span class="sxs-lookup"><span data-stu-id="b068c-116">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="b068c-117">Ausnahmen und Ausnahmebehandlung</span><span class="sxs-lookup"><span data-stu-id="b068c-117">Exceptions and Exception Handling</span></span>](./index.md)
- [<span data-ttu-id="b068c-118">Ausnahmebehandlung</span><span class="sxs-lookup"><span data-stu-id="b068c-118">Exception Handling</span></span>](./exception-handling.md)
