---
title: Verwenden von Ausnahmen – C#-Programmierhandbuch
description: Erfahren Sie, wie Sie Ausnahmen verwenden. Ausnahmen werden von Code ausgelöst, der auf einen Fehler stößt, und von Code abgefangen, der den Fehler behebt.
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#], about exception handling
- exceptions [C#], about exceptions
ms.assetid: 71472c62-320a-470a-97d2-67995180389d
ms.openlocfilehash: fb45381f1c6cfa2f27d036ead8e662b7a0d8d924
ms.sourcegitcommit: 6f58a5f75ceeb936f8ee5b786e9adb81a9a3bee9
ms.translationtype: HT
ms.contentlocale: de-DE
ms.lasthandoff: 07/28/2020
ms.locfileid: "87303373"
---
# <a name="use-exceptions-c-programming-guide"></a><span data-ttu-id="e8220-104">Verwenden von Ausnahmen (C#-Programmierhandbuch)</span><span class="sxs-lookup"><span data-stu-id="e8220-104">Use exceptions (C# programming guide)</span></span>

<span data-ttu-id="e8220-105">In C# werden Fehler im Programm zur Laufzeit mithilfe von sogenannten Ausnahmen durch das Programm weitergegeben.</span><span class="sxs-lookup"><span data-stu-id="e8220-105">In C#, errors in the program at run time are propagated through the program by using a mechanism called exceptions.</span></span> <span data-ttu-id="e8220-106">Ausnahmen werden von Code ausgelöst, der auf einen Fehler stößt. Sie werden von Code abgefangen, der den Fehler beheben kann.</span><span class="sxs-lookup"><span data-stu-id="e8220-106">Exceptions are thrown by code that encounters an error and caught by code that can correct the error.</span></span> <span data-ttu-id="e8220-107">Ausnahmen können durch die .NET-Runtime oder durch Code in einem Programm ausgelöst werden.</span><span class="sxs-lookup"><span data-stu-id="e8220-107">Exceptions can be thrown by the .NET runtime or by code in a program.</span></span> <span data-ttu-id="e8220-108">Sobald eine Ausnahme ausgelöst wird, wird sie in der Aufrufliste nach oben weitergegeben, bis eine `catch`-Anweisung für die Ausnahme gefunden wird.</span><span class="sxs-lookup"><span data-stu-id="e8220-108">Once an exception is thrown, it propagates up the call stack until a `catch` statement for the exception is found.</span></span> <span data-ttu-id="e8220-109">Nicht abgefangene Ausnahmen werden von einem generischen Ausnahmehandler behandelt, der vom System bereitgestellt wird, das ein Dialogfeld anzeigt.</span><span class="sxs-lookup"><span data-stu-id="e8220-109">Uncaught exceptions are handled by a generic exception handler provided by the system that displays a dialog box.</span></span>  
  
 <span data-ttu-id="e8220-110">Ausnahmen werden von Klassen dargestellt, die von <xref:System.Exception> abgeleitet sind.</span><span class="sxs-lookup"><span data-stu-id="e8220-110">Exceptions are represented by classes derived from <xref:System.Exception>.</span></span> <span data-ttu-id="e8220-111">Diese Klasse bestimmt den Typ der Ausnahme und enthält Eigenschaften, die über Details zur Ausnahme verfügen.</span><span class="sxs-lookup"><span data-stu-id="e8220-111">This class identifies the type of exception and contains properties that have details about the exception.</span></span> <span data-ttu-id="e8220-112">Das Auslösen einer Ausnahme umfasst das Erstellen einer Instanz einer von einer Ausnahme abgeleiteten Klasse, das optionale Konfigurieren von Eigenschaften der Ausnahme und das Auslösen des Objekts mithilfe des Schlüsselworts `throw`.</span><span class="sxs-lookup"><span data-stu-id="e8220-112">Throwing an exception involves creating an instance of an exception-derived class, optionally configuring properties of the exception, and then throwing the object by using the `throw` keyword.</span></span> <span data-ttu-id="e8220-113">Zum Beispiel:</span><span class="sxs-lookup"><span data-stu-id="e8220-113">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#1](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#1)]  
  
 <span data-ttu-id="e8220-114">Nachdem eine Ausnahme ausgelöst wird, überprüft die Runtime die aktuelle Anweisung, um festzustellen, ob sie sich in einem `try`-Block befindet.</span><span class="sxs-lookup"><span data-stu-id="e8220-114">After an exception is thrown, the runtime checks the current statement to see whether it is within a `try` block.</span></span> <span data-ttu-id="e8220-115">Falls dies der Fall ist, werden alle mit dem `try`-Block verknüpften `catch`-Blöcke überprüft, um festzustellen, ob sie die Ausnahme abfangen können.</span><span class="sxs-lookup"><span data-stu-id="e8220-115">If it is, any `catch` blocks associated with the `try` block are checked to see whether they can catch the exception.</span></span> <span data-ttu-id="e8220-116">`Catch`-Blöcke geben normalerweise Ausnahmetypen an; wenn der Typ des `catch`-Blocks der gleiche Typ ist wie die Ausnahme oder die Basisklasse der Ausnahme, kann der `catch`-Block die Methode behandeln.</span><span class="sxs-lookup"><span data-stu-id="e8220-116">`Catch` blocks typically specify exception types; if the type of the `catch` block is the same type as the exception, or a base class of the exception, the `catch` block can handle the method.</span></span> <span data-ttu-id="e8220-117">Zum Beispiel:</span><span class="sxs-lookup"><span data-stu-id="e8220-117">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#2](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#2)]  
  
 <span data-ttu-id="e8220-118">Wenn sich die Anweisung, die eine Ausnahme auslöst, nicht innerhalb eines `try`-Blocks befindet, oder der `try`-Block, der sie umfasst, über keinen übereinstimmenden `catch`-Block verfügt, überprüft die Runtime die aufrufende Methode auf eine `try`-Anweisung und `catch`-Blöcke.</span><span class="sxs-lookup"><span data-stu-id="e8220-118">If the statement that throws an exception is not within a `try` block or if the `try` block that encloses it has no matching `catch` block, the runtime checks the calling method for a `try` statement and `catch` blocks.</span></span> <span data-ttu-id="e8220-119">Die Runtime geht die Aufrufliste weiter nach oben durch und sucht nach einem kompatiblen `catch`-Block.</span><span class="sxs-lookup"><span data-stu-id="e8220-119">The runtime continues up the calling stack, searching for a compatible `catch` block.</span></span> <span data-ttu-id="e8220-120">Nachdem der `catch`-Block gefunden und ausgeführt wurde, wird die Steuerung an die nächste Anweisung nach diesem `catch`-Block weitergegeben.</span><span class="sxs-lookup"><span data-stu-id="e8220-120">After the `catch` block is found and executed, control is passed to the next statement after that `catch` block.</span></span>  
  
 <span data-ttu-id="e8220-121">Eine `try`-Anweisung kann mehr als einen `catch`-Block enthalten.</span><span class="sxs-lookup"><span data-stu-id="e8220-121">A `try` statement can contain more than one `catch` block.</span></span> <span data-ttu-id="e8220-122">Die erste `catch`-Anweisung, die die Ausnahme behandelt, wird ausgeführt; alle folgenden `catch`-Anweisungen werden ignoriert, selbst wenn sie kompatibel sind.</span><span class="sxs-lookup"><span data-stu-id="e8220-122">The first `catch` statement that can handle the exception is executed; any following `catch` statements, even if they are compatible, are ignored.</span></span> <span data-ttu-id="e8220-123">Daher sollten catch-Blöcke immer vom spezifischsten Element (oder am meisten abgeleiteten) zum am wenigsten spezifischen sortiert werden.</span><span class="sxs-lookup"><span data-stu-id="e8220-123">Therefore, catch blocks should always be ordered from most specific (or most-derived) to least specific.</span></span> <span data-ttu-id="e8220-124">Zum Beispiel:</span><span class="sxs-lookup"><span data-stu-id="e8220-124">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#3](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#3)]  
  
 <span data-ttu-id="e8220-125">Bevor der `catch`-Block ausgeführt wird prüft die Runtime auf `finally`-Blöcke.</span><span class="sxs-lookup"><span data-stu-id="e8220-125">Before the `catch` block is executed, the runtime checks for `finally` blocks.</span></span> <span data-ttu-id="e8220-126">`Finally`-Blöcke ermöglichen dem Programmierer, mehrdeutige Zustände zu bereinigen, die möglicherweise von einem abgebrochenen `try`-Block übrig sind, oder externe Ressourcen freizugeben (z.B. Grafikhandles, Datenbankverbindungen oder Dateistreams), ohne auf Garbage Collector in der Runtime zum Finalisieren der Objekte zu warten.</span><span class="sxs-lookup"><span data-stu-id="e8220-126">`Finally` blocks enable the programmer to clean up any ambiguous state that could be left over from an aborted `try` block, or to release any external resources (such as graphics handles, database connections or file streams) without waiting for the garbage collector in the runtime to finalize the objects.</span></span> <span data-ttu-id="e8220-127">Zum Beispiel:</span><span class="sxs-lookup"><span data-stu-id="e8220-127">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#4](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#4)]  
  
 <span data-ttu-id="e8220-128">Wenn `WriteByte()` eine Ausnahme auslöst, schlägt der Code im zweiten `try`-Block fehl, der versucht, die Datei erneut zu öffnen, wenn `file.Close()` nicht aufgerufen wird. Die Datei bleibt gesperrt.</span><span class="sxs-lookup"><span data-stu-id="e8220-128">If `WriteByte()` threw an exception, the code in the second `try` block that tries to reopen the file would fail if `file.Close()` is not called, and the file would remain locked.</span></span> <span data-ttu-id="e8220-129">Da `finally`-Blocke ausgeführt werden, selbst wenn eine Ausnahme ausgelöst wird, ermöglicht es der `finally`-Block im vorherigen Beispiel, dass die Datei korrekt geschlossen wird und trägt so zur Fehlervermeidung bei.</span><span class="sxs-lookup"><span data-stu-id="e8220-129">Because `finally` blocks are executed even if an exception is thrown, the `finally` block in the previous example allows for the file to be closed correctly and helps avoid an error.</span></span>  
  
 <span data-ttu-id="e8220-130">Wenn in der Aufrufliste kein kompatibler `catch`-Block gefunden wird, nachdem eine Ausnahme ausgelöst wird, tritt eine der folgenden Situationen auf:</span><span class="sxs-lookup"><span data-stu-id="e8220-130">If no compatible `catch` block is found on the call stack after an exception is thrown, one of three things occurs:</span></span>  
  
- <span data-ttu-id="e8220-131">Wenn die Ausnahme sich in einem Finalizer befindet, wird der Finalizer abgebrochen und der Basisfinalizer (sofern vorhanden) aufgerufen.</span><span class="sxs-lookup"><span data-stu-id="e8220-131">If the exception is within a finalizer, the finalizer is aborted and the base finalizer, if any, is called.</span></span>  
  
- <span data-ttu-id="e8220-132">Wenn die Aufrufliste einen statischen Konstruktor oder einen statischen Feldinitialisierer enthält, wird <xref:System.TypeInitializationException> ausgelöst und die ursprüngliche Ausnahme der <xref:System.Exception.InnerException%2A>-Eigenschaft der neuen Ausnahme zugewiesen.</span><span class="sxs-lookup"><span data-stu-id="e8220-132">If the call stack contains a static constructor, or a static field initializer, a <xref:System.TypeInitializationException> is thrown, with the original exception assigned to the <xref:System.Exception.InnerException%2A> property of the new exception.</span></span>  
  
- <span data-ttu-id="e8220-133">Wenn der Anfang des Threads erreicht wird, wird der Thread beendet.</span><span class="sxs-lookup"><span data-stu-id="e8220-133">If the start of the thread is reached, the thread is terminated.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="e8220-134">Siehe auch</span><span class="sxs-lookup"><span data-stu-id="e8220-134">See also</span></span>

- [<span data-ttu-id="e8220-135">C#-Programmierhandbuch</span><span class="sxs-lookup"><span data-stu-id="e8220-135">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="e8220-136">Ausnahmen und Ausnahmebehandlung</span><span class="sxs-lookup"><span data-stu-id="e8220-136">Exceptions and Exception Handling</span></span>](./index.md)
